services:
  foxglove:
    image: andersonjwan/foxglove:2.7
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["graphics", "utility", "display", "video", "compute"]

networks:
  ros-network:
    name: ros-network
    driver: bridge
